### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/config.rs:17:18

### ISSUE THREAD

**Issue by callmeadi** [tidb-incubator/tidis#88]
Config { server: Server { listen: Some("0.0.0.0"), port: Some(6666), tls_listen: Some("0.0.0.0"), tls_port: Some(6443), tls_key_file: Some(""), tls_cert_file: Some(""), tls_auth_client: Some(false), tls_ca_cert_file: Some(""), pd_addrs: Some("basic-pd:2379"), instance_id: Some("1"), prometheus_listen: Some("0.0.0.0"), prometheus_port: Some(8080), password: None, log_level: Some("info"), log_file: Some("tikv-service.log"), cluster_broadcast_addr: None, cluster_topology_interval: None, cluster_topology_expire: None, meta_key_number: None }, backend: Backend { timeout: None, ca_file: None, cert_file: None, key_file: None, conn_concurrency: None, use_txn_api: None, use_async_commit: Some(true), try_one_pc_commit: Some(true), use_pessimistic_txn: Some(false), local_pool_number: Some(8), completion_queue_size: Some(1), grpc_keepalive_time: Some(10000), grpc_keepalive_timeout: Some(2000), allow_batch: Some(true), overload_threshold: None, max_batch_wait_time: Some(10), max_batch_size: Some(20), max_inflight_requests: Some(10000), txn_retry_count: Some(2), txn_region_backoff_delay_ms: Some(2), txn_region_backoff_delay_attemps: Some(5), txn_lock_backoff_delay_ms: Some(2), txn_lock_backoff_delay_attemps: Some(5), cmd_lrem_length_limit: None, cmd_linsert_length_limit: None, async_deletion_enabled: None, async_gc_worker_number: None, async_gc_worker_queue_size: None, async_gc_interval: None, async_del_list_threshold: None, async_del_hash_threshold: None, async_del_set_threshold: None, async_del_zset_threshold: None, async_expire_list_threshold: None, async_expire_hash_threshold: None, async_expire_set_threshold: None, async_expire_zset_threshold: None } }
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/config.rs:17:18
stack backtrace:
   0:     0x5641a28bfe85 - std::backtrace_rs::backtrace::libunwind::trace::hc5f0e1506f4edb39
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x5641a28bfe85 - std::backtrace_rs::backtrace::trace_unsynchronized::h53b1c5dc3c06560b
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5641a28bfe85 - std::sys_common::backtrace::_print_fmt::h1a7d5f48906eae70
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5641a28bfe85 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hed9a08d0af811fa5
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5641a25c12bc - core::fmt::write::h574d7e8060e08389
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/core/src/fmt/mod.rs:1198:17
   5:     0x5641a28ba875 - std::io::Write::write_fmt::h3266c77374172c32
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/io/mod.rs:1672:15
   6:     0x5641a28c15e1 - std::sys_common::backtrace::_print::h745319fa404abc88
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5641a28c15e1 - std::sys_common::backtrace::print::h42f1b482778349d6
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5641a28c15e1 - std::panicking::default_hook::{{closure}}::hf42ee92d109b18cd
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:295:22
   9:     0x5641a28c12e2 - std::panicking::default_hook::heb8c1646fafa37cf
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:314:9
  10:     0x5641a28c1c05 - std::panicking::rust_panic_with_hook::h92fcad6ddbd25f63
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:698:17
  11:     0x5641a28c1b04 - std::panicking::begin_panic_handler::{{closure}}::hf30199cc9cd78007
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:588:13
  12:     0x5641a28c0404 - std::sys_common::backtrace::__rust_end_short_backtrace::h98e4e812e85c2d18
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5641a28c1862 - rust_begin_unwind
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:584:5
  14:     0x5641a2131933 - core::panicking::panic_fmt::h1627e39d69366ab1
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/core/src/panicking.rs:142:14
  15:     0x5641a2131a83 - core::result::unwrap_failed::h2204b6a125c3a2d0
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/core/src/result.rs:1814:5
  16:     0x5641a29113f8 - std::sync::once::Once::call_once::{{closure}}::h49b5f817f97d7bf1
  17:     0x5641a2145857 - std::sync::once::Once::call_inner::h74c7da7f2846c57d
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/sync/once.rs:434:21
  18:     0x5641a24506fd - tidis_server::main::{{closure}}::hbb9ccba715ebdc04
  19:     0x5641a2458e7b - std::thread::local::LocalKey<T>::with::h8862b2e7b4b48003
  20:     0x5641a2501198 - tokio::park::thread::CachedParkThread::block_on::hba951e378d918c40
  21:     0x5641a2460abf - tokio::runtime::thread_pool::ThreadPool::block_on::h8fb9eebe21f032d6
  22:     0x5641a2173ac8 - tokio::runtime::Runtime::block_on::ha69bceff291e9731
  23:     0x5641a21e3654 - tidis_server::main::h43630419fa303ff1
  24:     0x5641a2173be3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0960f520f1deb7f5
  25:     0x5641a21ea539 - std::rt::lang_start::{{closure}}::hc47d23f927dc6187
  26:     0x5641a28b67ff - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf7c3141f4fac8a1d
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/core/src/ops/function.rs:280:13
  27:     0x5641a28b67ff - std::panicking::try::do_call::hee900854d655c1eb
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:492:40
  28:     0x5641a28b67ff - std::panicking::try::h81f99697b06ffa19
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:456:19
  29:     0x5641a28b67ff - std::panic::catch_unwind::h456424d2b65bbb47
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panic.rs:137:14
  30:     0x5641a28b67ff - std::rt::lang_start_internal::{{closure}}::hfc1ba9f6ec042223
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/rt.rs:128:48
  31:     0x5641a28b67ff - std::panicking::try::do_call::hb3cd0ad13902daaf
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:492:40
  32:     0x5641a28b67ff - std::panicking::try::ha823b8c8b15583c8
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panicking.rs:456:19
  33:     0x5641a28b67ff - std::panic::catch_unwind::h7b4f4c25642b0e7a
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/panic.rs:137:14
  34:     0x5641a28b67ff - std::rt::lang_start_internal::he1611cbb74772eca
                               at /rustc/4d6d601c8a83284d6b23c253a3e2a060fd197316/library/std/src/rt.rs:128:20
  35:     0x5641a21e5ce2 - main
  36:     0x7fe064c493d5 - __libc_start_main
  37:     0x5641a2170077 - <unknown>

**Comment by callmeadi** [comment]
Write issue for the log file. Fixed by changing the path to /tmp/logfile
